# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 149c104d27a9b1a4bd03e1df7ad4357bb4239d23382866bc003eaaa58ce24ba65f36f4e54c288e22d7f2d60fea7ae904dd4e5705111736aba4233ad8610a0632

test:
  secret_key_base: 232d799289a6ba5fff21db7e13576fc3234d1be0408a2075d78bac8b0a7ce709131a92e70c58ff25a116faf0c4b4ea4a484edbd1e4780d62bbe6dc0a20f630b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
